package bankapp.View;

import bankapp.Model.Account;

import javax.swing.*;
import java.awt.*;
import java.text.NumberFormat;
import java.util.Locale;

public class CekSaldoView extends JFrame {

    public CekSaldoView(Account account, DashboardView parentView) {
        setTitle("Cek Saldo - Bank App");
        setSize(450, 300);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null); // Menempatkan window di tengah layar
        setResizable(false);
        setLayout(new BorderLayout());

        // Header
        JPanel headerPanel = new JPanel();
        headerPanel.setBackground(new Color(0, 123, 255));
        headerPanel.setPreferredSize(new Dimension(450, 60));
        headerPanel.setLayout(new BorderLayout());

        JLabel lblHeader = new JLabel("Cek Saldo", JLabel.CENTER);
        lblHeader.setFont(new Font("Arial", Font.BOLD, 20));
        lblHeader.setForeground(Color.WHITE);
        headerPanel.add(lblHeader, BorderLayout.CENTER);

        add(headerPanel, BorderLayout.NORTH);

        // Format saldo
        NumberFormat rupiahFormat = NumberFormat.getNumberInstance(new Locale("id", "ID"));
        String saldoFormatted = rupiahFormat.format(account.getSaldo());

        JPanel panelContent = new JPanel();
        panelContent.setLayout(new BoxLayout(panelContent, BoxLayout.Y_AXIS));
        panelContent.setBackground(Color.WHITE);
        panelContent.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        JLabel lblRekening = new JLabel("Nomor Rekening: " + account.getNomorRekening(), JLabel.CENTER);
        lblRekening.setFont(new Font("Arial", Font.PLAIN, 16));
        lblRekening.setAlignmentX(Component.CENTER_ALIGNMENT);

        JLabel lblSaldo = new JLabel("Saldo Anda: Rp " + saldoFormatted, JLabel.CENTER);
        lblSaldo.setFont(new Font("Arial", Font.BOLD, 20));
        lblSaldo.setForeground(new Color(34, 139, 34));
        lblSaldo.setAlignmentX(Component.CENTER_ALIGNMENT);

        panelContent.add(lblRekening);
        panelContent.add(Box.createRigidArea(new Dimension(0, 20)));
        panelContent.add(lblSaldo);

        add(panelContent, BorderLayout.CENTER);

        // Panel tombol
        JPanel bottomPanel = new JPanel();
        bottomPanel.setBackground(Color.WHITE);

        JButton btnBack = new JButton("Kembali");
        btnBack.setFont(new Font("Arial", Font.BOLD, 14));
        btnBack.setBackground(new Color(220, 53, 69));
        btnBack.setForeground(Color.WHITE);
        btnBack.setPreferredSize(new Dimension(120, 40));

        btnBack.addActionListener(e -> {
            parentView.setVisible(true);
            dispose();
        });

        bottomPanel.add(btnBack);

        add(bottomPanel, BorderLayout.SOUTH);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
