package bankapp.View;

import bankapp.Controller.AccountController;
import bankapp.Controller.SetorController;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import javax.swing.border.EmptyBorder;

public class SetorView extends JFrame {

    private JTextField txtNominal;
    private JLabel lblNomorRekening;
    private JButton btnSetor, btnKembali;
    private String nomorRekening;

    public SetorView(int userId, DashboardView dashboardView) {
        setTitle("Setor Tunai - Bank App");
        setSize(400, 250);  // Adjusted size since we removed the description field
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        // Retrieve account number based on user ID
        AccountController accountController = new AccountController();
        nomorRekening = accountController.getNomorRekeningByUserId(userId);

        if (nomorRekening == null) {
            JOptionPane.showMessageDialog(this, "Nomor rekening tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            dispose();
            return;
        }

        // Input panel
        JPanel panelInput = new JPanel(new GridLayout(2, 2, 10, 10));  // Adjusted to 2 rows for Nominal and Account Number
        panelInput.setBorder(new EmptyBorder(15, 15, 15, 15));
        panelInput.setBackground(Color.WHITE);

        JLabel lblRekening = new JLabel("Nomor Rekening:");
        lblRekening.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        panelInput.add(lblRekening);

        lblNomorRekening = new JLabel(nomorRekening);
        lblNomorRekening.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblNomorRekening.setForeground(Color.BLUE);
        panelInput.add(lblNomorRekening);

        JLabel lblNominal = new JLabel("Nominal (Rp):");
        lblNominal.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        panelInput.add(lblNominal);

        txtNominal = new JTextField();
        txtNominal.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        panelInput.add(txtNominal);

        add(panelInput, BorderLayout.CENTER);

        // Button panel
        JPanel panelButtons = new JPanel(new FlowLayout(FlowLayout.CENTER, 20, 10));
        panelButtons.setBackground(Color.WHITE);

        btnSetor = new JButton("Setor");
        btnSetor.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnSetor.setBackground(new Color(0, 123, 255));
        btnSetor.setForeground(Color.WHITE);
        btnSetor.setPreferredSize(new Dimension(120, 40));

        btnKembali = new JButton("Kembali");
        btnKembali.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnKembali.setBackground(new Color(220, 53, 69));
        btnKembali.setForeground(Color.WHITE);
        btnKembali.setPreferredSize(new Dimension(120, 40));

        panelButtons.add(btnSetor);
        panelButtons.add(btnKembali);

        add(panelButtons, BorderLayout.SOUTH);

        // Setor button event handler
        btnSetor.addActionListener((ActionEvent e) -> {
            String nominalStr = txtNominal.getText().trim();

            if (nominalStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Field nominal harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                double nominal = Double.parseDouble(nominalStr);

                SetorController setorController = new SetorController();
                String result = setorController.setor(nomorRekening, nominal);

                JOptionPane.showMessageDialog(this, result, "Hasil Setor", JOptionPane.INFORMATION_MESSAGE);

                if (result.equals("Setoran berhasil.")) {
                    txtNominal.setText("");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Nominal harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        // Kembali button event handler
        btnKembali.addActionListener(e -> {
            dispose();
            dashboardView.setVisible(true);
        });

        // Set window location and visibility
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
